controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

sandbox:
    path: /sandbox
    controller: App\Controller\SandboxController::printRandomNumber